version: '3.1'

services:
  proxy:
    container_name: proxy
    image: nginx:1.23.1-alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx:/nginx/:ro
      - ./certbot:/certbot/:ro
    ports:
      - 80:80
      - 443:443
  ## CERTBOT FOR HTTPS:
  # certbot:
  #   container_name: certbot
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw
  #   # TODO: entrypoint: "/bin/sh -c 'while :; do sleep 24h; certbot renew; done'"
  ## NODEJS APP:
  # nodejsappka:
  #   container_name: nodejsappka
  #   build:
  #     context: ./nodejsappfolder
  php:
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php/src:/var/www/html/
  mariadb:
    container_name: mariadb
    image: mariadb:10.8.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: s3cretP4ss
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
